mysite/biblioteka/urls.py
from django.urls import path

from . import views


app_name = 'biblioteka'
urlpatterns = [
    path('', views.index, name='index'),
    path('ksiazki/', views.ksiazka, name='ksiazka'),
    path('<int:ksiazka_id>/egzemplarze', views.egzemplarze, name='egzemplarze'),
    path('<uuid:egz_id>/egzemplarzDetail', views.egzemplarzDetail, name='egzDetail'),
    #path('ksiazka_detail.html/<int:ksiazka_id>', views.ksiazkaDetail, name='ksiazkaDetail'),
    path('wydawnictwo/', views.wydawnictwo, name='wydawnictwo'),
    path('<int:wyd_id>/wydDetail', views.wydawnictwoDetail, name='wydDetail'),
    path('usunWyd/<int:wyd_id>', views.usunWydawnictwo, name='usunWyd'),
    path('edycjaWyd/<int:wyd_id>', views.edycjaWydawnictwo, name='edycjaWyd'),
    path('formularzWyd/', views.formWydawnictwo, name='formWyd'),
    path('jezyk/', views.jezyk, name='jezyk'),
    path('formularzJezyk/', views.formJezyk, name='formJezyk'),
    path('gatunek/', views.gatunek, name='gatunek'),
    path('<int:gat_id>/gatunekDetail', views.gatunekDetail, name='gatDetail'),
    path('formularzGatunek/', views.formGatunek, name='formGatunek'),
    path('usunGatunek/<int:gat_id>', views.usunGatunek, name='usunGat'),
    path('edycjaGatunek/<int:gat_id>', views.edycjaGatunek, name='edycjaGat'),
    path('autor/', views.autor, name='autor'),
    path('<int:autor_id>/autorDetail', views.autorDetail, name='autorDetail'),
    path('formularzAutor/', views.formAutor, name='formAutor'),
    path('usunAutor/<int:autor_id>', views.usunAutor, name='usun'),
    path('edycjaAutor/<int:autor_id>', views.edycjaAutor, name='edycja'),
    path('formularzKsiazka/', views.formKsiazka, name='formKsiazka'), 
    path('formularzEgz/', views.formEgzemplarz, name='formEgzemplarz'),
    path('usunEgz/<uuid:egz_id>', views.usunEgzemplarz, name='usun'),
    path('edycjaEgz/<uuid:egz_id>', views.edycjaEgzemplarz, name='edycja'),
    path('komEgz/<uuid:egz_id>', views.dodajKomentarz, name='komentarz'),
    path('register/',views.register, name='register'),
    path('customer_register/',views.czytelnik_register.as_view(), name='customer_register'),
    path('employee_register/',views.bibliotekarz_register.as_view(), name='employee_register'),
    path('login/',views.login_request, name='login'),
    path('logout/',views.logout_view, name='logout'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('biblioteka/', include('biblioteka.urls')),
    path('admin/', admin.site.urls), 
]

mysite/biblioteka/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

# Create your models here.

class Autor(models.Model):
    imie = models.CharField(max_length=20)
    nazwisko = models.CharField(max_length=30)
    data_urodzenia = models.DateField('Data urodzenia')
    data_smierci = models.DateField('Data smierci', null=True, blank=True)
    
    def __str__(self):
        return '{0}, {1}'.format(self.imie, self.nazwisko)
    
class Gatunek(models.Model):
    nazwa_gatunku = models.CharField(max_length=100)

    def __str__(self):
        return self.nazwa_gatunku
    

class Ksiazka(models.Model):
    tytul = models.CharField(max_length=100)
    
    autor = models.ManyToManyField(Autor)
    gatunek = models.ManyToManyField(Gatunek)
    
    def __str__(self):
        return self.tytul
    
    
class Wydawnictwo(models.Model):
    nazwa_wydawnictwa = models.CharField(max_length=100)
        
    def __str__(self):
        return self.nazwa_wydawnictwa

    
class Jezyk(models.Model):
    nazwa_jezyka = models.CharField(max_length=20)
    
    def __str__(self):
        return self.nazwa_jezyka
    
class User(AbstractUser):
    is_czytelnik = models.BooleanField(default=False)
    is_bibliotekarz = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

class Czytelnik(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    phone_number = models.CharField(max_length=20)

class Bibliotekarz(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    phone_number = models.CharField(max_length=20)
    
class Egzemplarz(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unikalny klucz')
    data = models.DateField('Data wydania', null=True, blank=True)
    wydawnictwo = models.ForeignKey(Wydawnictwo, on_delete=models.CASCADE)
    jezyk = models.ForeignKey(Jezyk, on_delete=models.CASCADE)
    ksiazka = models.ForeignKey(Ksiazka, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    
    DOSTEPNOSC_STATUS = (
        ('d', 'Dostepna'),
        ('nd', 'Niedostepna'),
    )

    status = models.CharField(
        max_length=2,
        choices=DOSTEPNOSC_STATUS,
        blank=True,
        default='d',
        help_text='Dostepnosc',
    )
    
    def __str__(self):
        return self.ksiazka.tytul
    
class Ocena(models.Model):
    komentarz = models.TextField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    egzemplarz = models.ForeignKey(Egzemplarz, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.komentarz
    




    
  

mysite/biblioteka/views.py
from django.http import HttpResponse
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.views.generic import CreateView
from .form import CzytelnikSignUpForm, BibliotekarzSignUpForm, AutorForm, KsiazkaForm, EgzemplarzForm, WydawnictwoForm, JezykForm, GatunekForm, OcenaForm
from django.contrib.auth.forms import AuthenticationForm
from .models import User, Ksiazka, Wydawnictwo, Egzemplarz, Autor, Bibliotekarz, Czytelnik, Gatunek, Jezyk, Ocena
from django.contrib.auth.decorators import login_required
from .decorators import czytelnik_required, bibliotekarz_required

# Create your views here.


def index(request):
    return render(request, 'biblioteka/index.html')

def ksiazka(request):
    ksiazka_lista = Ksiazka.objects.all()
    context = {'ksiazka_lista': ksiazka_lista}
    return render(request, 'biblioteka/ksiazki.html', context)

def wydawnictwo(request):
    wyd_lista = Wydawnictwo.objects.all()
    return render(request, 'biblioteka/wydawnictwo.html', {'wyd_lista': wyd_lista})

def wydawnictwoDetail(request, wyd_id):
    wydawnictwo = get_object_or_404(Wydawnictwo, pk=wyd_id)
    return render(request, 'biblioteka/wydawnictwoDetail.html', {'wyd': wydawnictwo})

def jezyk(request):
    jezyk_lista = Jezyk.objects.all()
    return render(request, 'biblioteka/jezyk.html', {'jezyk_lista': jezyk_lista})

def gatunek(request):
    gat_lista = Gatunek.objects.all()
    return render(request, 'biblioteka/gatunek.html', {'gat_lista': gat_lista})

def gatunekDetail(request, gat_id):
    gatunek = get_object_or_404(Gatunek, pk=gat_id)
    return render(request, 'biblioteka/gatunekDetail.html', {'gatunek': gatunek})

def egzemplarze(request, ksiazka_id):
    egzemplarz_lista = Egzemplarz.objects.all()
    ksiazka = get_object_or_404(Ksiazka, pk=ksiazka_id)
    gatunek_lista = ksiazka.gatunek.all()
    autor_lista = ksiazka.autor.all()
    context ={'egzemplarz_lista': egzemplarz_lista, 'ksiazka': ksiazka, 'gatunek_lista': gatunek_lista,
              'autor_lista': autor_lista}
    return render(request, 'biblioteka/egzemplarze.html', context)

def egzemplarzDetail(request, egz_id):
    egzemplarz = get_object_or_404(Egzemplarz, pk=egz_id)
    ocena_lista = Ocena.objects.all()
    return render(request, 'biblioteka/egzemplarzDetail.html', {'egz': egzemplarz, 'ocena_lista': ocena_lista})

def autor(request):
    autor_lista = Autor.objects.all()
    context = {'autor_lista': autor_lista}
    return render(request, 'biblioteka/autor.html', context)

def autorDetail(request, autor_id):
    autor = get_object_or_404(Autor, pk=autor_id)
    return render(request, 'biblioteka/autorDetail.html', {'autor': autor})


def formAutor(request):
    formularz = AutorForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
    return render(request, 'biblioteka/formularz.html', {'form': formularz}) 
        
def edycjaAutor(request, autor_id):
    autor = get_object_or_404(Autor, pk=autor_id)
    formularz = AutorForm(request.POST or None, request.FILES or None, instance = autor)
    if formularz.is_valid():
        formularz.save()
        return redirect('biblioteka:autor')
    return render(request, 'biblioteka/edycja.html', {'form': formularz})
    
def usunAutor(request, autor_id):
    autor = get_object_or_404(Autor, pk=autor_id)
    if request.method == "POST":
        autor.delete()
        return redirect('biblioteka:autor')
    return render(request, 'biblioteka/usun.html', {'autor_id': autor_id})

def formKsiazka(request):
    formularz = KsiazkaForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
    return render(request, 'biblioteka/formularz.html', {'form': formularz})

def formEgzemplarz(request):
    formularz = EgzemplarzForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
    return render(request, 'biblioteka/formularz.html', {'form': formularz})

def edycjaEgzemplarz(request, egz_id):
    egzemplarz = get_object_or_404(Egzemplarz, pk=egz_id)
    formularz = EgzemplarzForm(request.POST or None, request.FILES or None, instance = egzemplarz)
    if formularz.is_valid():
        formularz.save()
        return redirect('biblioteka:egzemplarze')
    return render(request, 'biblioteka/edycja.html', {'form': formularz})
    
def usunEgzemplarz(request, egz_id):
    egzemplarz = get_object_or_404(Egzemplarz, pk=egz_id)
    if request.method == "POST":
        egzemplarz.delete()
        return redirect('biblioteka:ksiazka')
    return render(request, 'biblioteka/usun.html')

def dodajKomentarz(request, egz_id):
    egzemplarz = get_object_or_404(Egzemplarz, pk=egz_id)
    formularz = OcenaForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
        o = Ocena(komentarz = formularz.cleaned_data['komentarz'], user = request.user)
        o.save()
        egzemplarz.ocena = o
    return render(request, 'biblioteka/formularz.html', {'form': formularz}) 

def formWydawnictwo(request): 
    formularz = WydawnictwoForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
    return render(request, 'biblioteka/formularz.html', {'form': formularz})

def edycjaWydawnictwo(request, wyd_id):
    wydawnictwo = get_object_or_404(Wydawnictwo, pk=wyd_id)
    formularz = WydawnictwoForm(request.POST or None, request.FILES or None, instance = wydawnictwo)
    if formularz.is_valid():
        formularz.save()
        return redirect('biblioteka:wydawnictwo')
    return render(request, 'biblioteka/edycja.html', {'form': formularz})
    
def usunWydawnictwo(request, wyd_id):
    wydawnictwo = get_object_or_404(Wydawnictwo, pk=wyd_id)
    if request.method == "POST":
        wydawnictwo.delete()
        return redirect('biblioteka:wydawnictwo')
    return render(request, 'biblioteka/usun.html', {'wyd_id': wyd_id})

def formJezyk(request): 
    formularz = JezykForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
    return render(request, 'biblioteka/formularz.html', {'form': formularz})

def formGatunek(request): 
    formularz = GatunekForm(request.POST or None)
    if formularz.is_valid():
        formularz.save()
    return render(request, 'biblioteka/formularz.html', {'form': formularz})

def edycjaGatunek(request, gat_id):
    gatunek = get_object_or_404(Gatunek, pk=gat_id)
    formularz = GatunekForm(request.POST or None, request.FILES or None, instance = gatunek)
    if formularz.is_valid():
        formularz.save()
        return redirect('biblioteka:gatunek')
    return render(request, 'biblioteka/edycja.html', {'form': formularz})
    
def usunGatunek(request, gat_id):
    gatunek = get_object_or_404(Gatunek, pk=gat_id)
    if request.method == "POST":
        gatunek.delete()
        return redirect('biblioteka:gatunek')
    return render(request, 'biblioteka/usun.html', {'gat_id': gat_id})

def register(request):
    return render(request, 'biblioteka/register.html')

class czytelnik_register(CreateView):
    model = User
    form_class = CzytelnikSignUpForm
    template_name = 'biblioteka/czytelnik_rejestracja.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('biblioteka:index')

class bibliotekarz_register(CreateView):
    model = User
    form_class = BibliotekarzSignUpForm
    template_name = 'biblioteka/bibliotekarz_rejestracja.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('biblioteka:index') 


def login_request(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None :
                login(request,user)
                return redirect('biblioteka:index')
            else:
                messages.error(request,"Invalid username or password")
        else:
                messages.error(request,"Invalid username or password")
    return render(request, 'biblioteka/login.html',
    context={'form':AuthenticationForm()})

def logout_view(request):
    logout(request)
    return redirect('biblioteka:index')

mysite/biblioteka/templates/biblioteka/autor.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="ksiazki">
                <div class="sekcja">
                    {% if autor_lista %}
                    <ul>
                    {% if request.user.is_authenticated %}
                        <p><a href="{% url 'biblioteka:formAutor' %}">Dodaj autora</a></p>
                    {% endif %}
                    {% for autor in autor_lista %}
                        <li>
                            <a href="{% url 'biblioteka:autorDetail' autor.id %}">{{ autor.imie }} {{autor.nazwisko}}</a>
                        </li> 
                    {% endfor %}
                    </ul>
                {% else %}
                    <h1>Brak autorów</h1>
                {% endif %}                
                </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>

mysite/biblioteka/templates/biblioteka/autorDetail.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="ksiazki">
                <div class="sekcja">

                    <ul>
                        <li>
                            {{ autor.imie }} {{autor.nazwisko}}<br>
                            {{autor.data_urodzenia}} - {{autor.data_smierci}}
                            {% if request.user.is_authenticated %}
                            <p><a href="{% url 'biblioteka:usun' autor.id %}">Usuń</a></p>
                            <p><a href="{% url 'biblioteka:edycja' autor.id %}">Edytuj</a></p>
                            {% endif %}
                        </li> 
                    </ul>              
                 </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>

mysite/biblioteka/templates/biblioteka/edycja.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="formularz">
                <div class="sekcja">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit">Zaktualizuj</button>
                        </form>   
                </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>

mysite/biblioteka/templates/biblioteka/egzemplarzDetail.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="ksiazki">
                <div class="sekcja">
                    <ul>
                        <li>
                            {{ egz.ksiazka.tytul }}, {{egz.wydanie.wydawnictwo}}<br>
                            Data wydania:  {{ egz.data }}<br>
                            Dostępność: {{egz.status}}<br>
                            Komentarze: {{egz.ocena.komentarz}}
                            {% if ocena_lista %}
                            {% for o in ocena_lista %}
                                {% if o.egzemplarz == egz %}
                                    <br> {{o.komentarz}}
                                {% endif %}
                            {% endfor %}
                            {% endif %}
                            {% if request.user.is_authenticated %}
                            <p><a href="{% url 'biblioteka:usun' egz.id %}">Usuń</a></p>
                            <p><a href="{% url 'biblioteka:edycja' egz.id %}">Edytuj</a></p>
                            <p><a href="{% url 'biblioteka:komentarz' egz.id %}">Dodajj komentarz</a></p>
                            {% endif %}
                        </li> 
                    </ul>              
                 </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>

mysite/biblioteka/templates/biblioteka/gatunek.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="ksiazki">
                <div class="sekcja">
                    <ul>
                    {% if request.user.is_authenticated %}
                        <p><a href="{% url 'biblioteka:formGatunek' %}">Dodaj gatunek</a></p>
                    {% endif %}
                    {% if gat_lista %}
                    {% for g in gat_lista %}
                        <li>
                            <a href="{% url 'biblioteka:gatDetail' g.id %}">{{ g.nazwa_gatunku }}</a>
                        </li> 
                    {% endfor %}
                    </ul>
                {% else %}
                    <h1>Brak gatunków</h1>
                {% endif %}                
                </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>

mysite/biblioteka/templates/biblioteka/gatunekDetail.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="ksiazki">
                <div class="sekcja">

                    <ul>
                        <li>
                            {{gatunek.nazwa_gatunku}}
                            {% if request.user.is_authenticated %}
                                <p><a href="{% url 'biblioteka:usunGat' gatunek.id %}">Usuń</a></p>
                                <p><a href="{% url 'biblioteka:edycjaGat' gatunek.id %}">Edytuj</a></p>
                            {% endif %}
                        </li> 
                    </ul>              
                 </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>

mysite/biblioteka/templates/biblioteka/wydawnictwoDetail.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <title>Katalog biblioteki</title>

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'biblioteka/index.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'biblioteka:index' %}">Strona główna</a></li>
                    <li><a href="{% url 'biblioteka:ksiazka' %}">Książki</a></li>
                    <li><a href="{% url 'biblioteka:autor' %}">Autorzy</a></li>
                    <li><a href="{% url 'biblioteka:wydawnictwo' %}">Wydawnictwa</a></li>
                    <li><a href="{% url 'biblioteka:gatunek' %}">Gatunki</a></li>
                    <li><a href="{% url 'biblioteka:jezyk' %}">Jezyki</a></li>
                    <li><a href="{% url 'biblioteka:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'biblioteka:logout' %}">Wyloguj się</a></li>
                    <li><a href="{% url 'biblioteka:register' %}">Rejestracja</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section id="ksiazki">
                <div class="sekcja">

                    <ul>
                        <li>
                            {{wyd.nazwa_wydawnictwa}}
                            {% if request.user.is_authenticated %}
                            <p><a href="{% url 'biblioteka:usunWyd' wyd.id %}">Usuń</a></p>
                            <p><a href="{% url 'biblioteka:edycjaWyd' wyd.id %}">Edytuj</a></p>
                            {% endif %}
                        </li> 
                    </ul>              
                 </div>
            </section>
        </main>
        <footer>
            Aplikacje bazodanowe - projekt
        </footer>
    </body>
</html>